### PR TITLE
Remove cudatoolkit-dev from recipe

### PR DESCRIPTION
**Pull request by bnemanich**
This addresses issue #3

### CODE REVIEW

**Review by jayfurmanek — APPROVED** [review]
Glad this one was easy!

**Review by jayfurmanek — APPROVED** [review]

**Review by jayfurmanek — APPROVED** [review]

**Review by npanpaliya — APPROVED** [review]

**Comment by npanpaliya** [comment]
Should build number be incremented for meta and select recipes?

**Comment by bnemanich** [comment]
I don't think that is necessary, since there is no difference in the recipes.

**Comment by jayfurmanek** [comment]
They should but only if the recipe for the meta package itself changes.

**Pull request merged**
